Revert "Update lz4 to version 1.10.0"
It doesn't compile:
```
/programs/datagen.c(1,1): error C1083: Cannot open source file: '..\..\..\programs\datagen.c': No such file or director
y [C:\gtk-build\build\x64\release\lz4\visual\vs2022\datagen\datagen.vcxproj]
```

This reverts commit 3c190c2a48606f224830cbb5d5e30c046fae45c4.